---
# YellowLight Template - Caution/Warning Actions
# Use this template for warnings, potential issues, or actions that require careful consideration

name: YellowLight
status: warning
priority: medium
color: "#FFFF00"

triggers:
  - type: warning
  - type: potential_issue
  - type: review_required
  - type: caution

actions:
  - name: "Assess Situation"
    description: "Evaluate the current state and potential risks"
    required: true
    
  - name: "Monitor Closely"
    description: "Keep a close watch on metrics and indicators"
    required: true
    
  - name: "Notify Relevant Team"
    description: "Inform team members who need to be aware"
    required: true
    channels:
      - slack
      - email
    
  - name: "Document Concerns"
    description: "Record observations and concerns"
    required: true
    
  - name: "Prepare Contingency"
    description: "Have backup plans ready if situation worsens"
    required: false

notification:
  template: "🟡 YELLOWLIGHT: Caution advised - {{issue_title}}"
  urgency: moderate
  
metadata:
  icon: "🟡"
  emoji: ":yellow_circle:"
  signal: "CAUTION"
